### ISSUE TITLE
Arnthor: new test case 1

### ISSUE THREAD

**Issue by AlbertoDubbini** [arnthor89/pygame#13]
Write a test for coverage improvement.
- Function initsysfonts_win32@66-139@src_py/sysfont.py (subject to possible change)

**Comment by arnthor89** [comment]
Since it's hard to measure complexity of this function I will change the function to improve coverage. The new function `match_font@379-411@src_py/sysfont.py`. I will, however, include the other tests as an added bonus if we want to create a pull request for the actual `pygame` project.

**Comment by AlbertoDubbini** [comment]
Closed by PR #35
