### ISSUE TITLE
Describe the 10 complex functions

### ISSUE THREAD

**Issue by AlbertoDubbini** [arnthor89/pygame#22]
Using Lizard we should list the top-10 method for CC (those function can be different from the other 10 that we're using for coverage improvement, coverage measurement and CC calculation) and describe them. In particular try to answer these questions:
- what is the purpose of the function?
- has the function only high CC or is it also long?
- do you think the complexity is due to the logic of the function or to a bad written code?
- can you think of a way to refactor the function so that the CC decreases?

**Comment by AlbertoDubbini** [comment]
================================================
  NLOC    CCN   token  PARAM  length  location
------------------------------------------------
     110     63   3344      1     119 test_elementwise@1397-1515@./test/math_test.py
     150     37    936      2     285 run@33-317@./test/test_utils/run_tests.py
      96     36    685      1     120 process_chunk@1706-1825@./test/test_utils/png.py
      92     33   2602      1     101 test_elementwise@474-574@./test/math_test.py
      91     33   2097      1     100 test_elementwise@576-675@./test/math_test.py
      83     29    487      3     192 from_array@1045-1236@./test/test_utils/png.py
     112     27   1025      0     165 main@20-184@./examples/blit_blends.py
     120     26    907      1     166 main@179-344@./examples/aliens.py
      71     25    528      1     121 main@146-266@./buildconfig/config_unix.py
     129     24   1225      1     158 test_blit_array@251-408@./test/surfarray_test.py

**Comment by AlbertoDubbini** [comment]
Most of them regard test or examples or configuration. So we must decide if we want to stay stuck to the request for the project (describe the 10 most complex function) or maybe take some degree of freedom and look for some more meaningful function from the src_py directory and list them only.
In this second case we would probably end up with some of the function we used for coverage improvement.

**Comment by tpetersonkth** [comment]
Here is lizard run without the test cases: https://pastebin.com/QdcfGuNH

Cyrille told us to not work on the tests for the description but to work with the top 10 most complex non-test functions.

These are:
```
  NLOC    CCN   token  PARAM  length  location  
------------------------------------------------
     112     27   1025      0     165 main@20-184@./examples/blit_blends.py
     120     26    907      1     166 main@179-344@./examples/aliens.py
      71     25    528      1     121 main@146-266@./buildconfig/config_unix.py
      50     24    370      4      59 writesetupfile@105-163@./buildconfig/config.py
      94     24    770      1     137 main@183-319@./examples/macosx/aliens_app_example/aliens.py
      47     24    403      3      62 main@6-67@./examples/scaletest.py
      92     23    543      3     130 draw@1025-1154@./src_py/sprite.py
      63     23    461      0      68 main@227-294@./buildconfig/config_msys.py
      75     23    558      0      99 main@47-145@./examples/textinput.py
      36     20    214      5      67 SysFont@296-362@./src_py/sysfont.py
```

**Comment by AlbertoDubbini** [comment]
I'm still a bit confused now 😅
Haven't we come to the conclusion that we can use the sam subset of 10 functions for all the tasks (i.e. describing, coverage measurement, coverage improvement through tests, refactoring)?

**Comment by pythonpsycho1337** [comment]
Yeah, you are right. Let's stick to that! :)

**Comment by tpetersonkth** [comment]
But we said that the refactoring had to be on two other functions though

**Comment by tpetersonkth** [comment]
Didn't we?

**Comment by AlbertoDubbini** [comment]
I think that at the end the decision is up to us. The instruction are not so clear

**Comment by AlbertoDubbini** [comment]
https://github.com/arnthor89/pygame/wiki/Functions'-list

**Comment by AlbertoDubbini** [comment]
Closed! Look at the [wiki](https://github.com/arnthor89/pygame/wiki)
