### ISSUE TITLE
Cyclomatic Complexity calculation

### ISSUE THREAD

**Issue by AlbertoDubbini** [arnthor89/pygame#6]
We need to calculate by hand the CC for 5 function taken from the 10 function we'll address and compare the result with the one obtained by Lizard.
I know how to do it so refers to me for questions.

**Comment by AlbertoDubbini** [comment]
[Wiki](https://github.com/arnthor89/pygame/wiki/Cyclomatic-Complexity)

**Comment by tpetersonkth** [comment]
We need to mention them in the report too.

**Comment by tpetersonkth** [comment]
I put them at the bottom of the report
